-- Surround, indent text objects, autopairs and formatting.

local function surround(name, lines, cursor, keys, expected)
  test("surround: " .. name, function(c)
    c:set_lines(lines)
    c:set_cursor(cursor[1], cursor[2])
    c:keys(keys)
    eq(expected, c:lines())
  end)
end

surround("ysiw( pads", { "foo bar" }, { 1, 0 }, "ysiw(", { "( foo ) bar" })
surround("ysiw) doesn't pad", { "foo bar" }, { 1, 4 }, "ysiw)", { "foo (bar)" })
surround("yss] keeps indent", { "  x = 1" }, { 1, 0 }, "yss]", { "  [x = 1]" })
surround("ds( removes padding", { "a ( foo ) b" }, { 1, 5 }, "ds(", { "a foo b" })
surround("cs)]", { "a (foo) b" }, { 1, 4 }, "cs)]", { "a [foo] b" })
surround("cs\"'", { 'say "hi" now' }, { 1, 5 }, "cs\"'", { "say 'hi' now" })
surround('ds" on the quote', { 'say "hi" now' }, { 1, 4 }, 'ds"', { "say hi now" })
surround("ds) picks the enclosing pair", { "f(a, g(b))" }, { 1, 2 }, "ds)", { "fa, g(b)" })
surround("visual S}", { "one two" }, { 1, 0 }, "viwS}", { "{one} two" })

test("surround: . repeats ys with the same pair", function(c)
  c:set_lines({ "one two three" })
  c:keys('ysiw"')
  c:set_cursor(1, 6)
  c:keys(".")
  eq({ '"one" "two" three' }, c:lines())
end)

test("indent: dii deletes the block", function(c)
  c:set_lines({ "def f():", "    a", "", "    b", "c" })
  c:set_cursor(2, 0)
  c:keys("dii")
  eq({ "def f():", "c" }, c:lines())
end)

test("indent: dai includes the header", function(c)
  c:set_lines({ "def f():", "    a", "    b", "c" })
  c:set_cursor(3, 0)
  c:keys("dai")
  eq({ "c" }, c:lines())
end)

test("autopairs: closing bracket steps over", function(c)
  c:keys("i")
  c:type("foo(x)")
  eq("foo(x)", c:line())
end)

test("autopairs: quotes pair, apostrophes don't", function(c)
  c:keys("i")
  c:type([["a" don't]])
  eq([["a" don't]], c:line())
end)

test("autopairs: backspace in an empty pair deletes both", function(c)
  c:keys("i")
  c:type("(")
  c:keys("<BS>")
  c:type("x")
  eq("x", c:line())
end)

test("autopairs: enter between brackets opens a line", function(c)
  c:keys("i")
  c:type("{")
  c:keys("<CR>")
  c:type("y")
  eq({ "{", "y", "}" }, vim.tbl_map(vim.trim, c:lines()))
end)

test("format: <leader>f trims trailing whitespace", function(c)
  c:set_lines({ "a   ", "b\t" })
  c:keys(" f")
  eq({ "a", "b" }, c:lines())
end)
