# waywall + Ninjabrain-Bot, configured declaratively from the waywall flake's
# home-manager modules.
#
# The waywall repo (github:malleum/waywall, checked out at ~/.config/waywall)
# owns the Lua engine, the overlay PNG generator and the MCSR JDK; this file is
# only the wiring: it feeds the stylix palette in and sets the geometry and
# keybinds. ~/.config/waywall/init.lua is generated -- it is gitignored in that
# repo, so the checkout and the generated file coexist in the same directory.
{inputs, ...}: {
  unify.modules.gam.home = {
    config,
    pkgs,
    ...
  }: let
    inherit (config.stylix) base16Scheme;

    c = name: "#${base16Scheme.${name}}";

    waywallPkgs = inputs.waywall.packages.${pkgs.stdenv.hostPlatform.system};

    # Every hotkey in the old prefs.xml was stored with location STANDARD, so
    # spell that out rather than leaving it to the UNKNOWN default -- the two
    # produce different codes and the bot would not recognise the key.
    stdKey = key: {
      inherit key;
      location = "STANDARD";
    };
  in {
    imports = [inputs.waywall.homeModules.default];

    home.packages = [waywallPkgs.cps-wl];

    # The JDK to point Prism's instances at. Deliberately *not* in
    # home.packages: it is a full JDK, so it collides with the openjdk another
    # package already puts in the profile (both ship lib/src.zip). A symlink
    # gives Prism a stable path to autodetect and keeps the store path GC-rooted
    # without putting a second `java` on PATH.
    #
    # Java path:      ~/.local/share/jdks/mcsr-graalvm/bin/java
    # Java arguments: nix eval --json github:malleum/waywall#mcsr-jdk.jvmArgs
    # Max heap:       nix eval github:malleum/waywall#mcsr-jdk.heapMegabytes
    home.file.".local/share/jdks/mcsr-graalvm".source = waywallPkgs.mcsr-jdk;

    programs.waywall = {
      enable = true;

      canvas = {
        width = 1920;
        height = 1080;
      };

      colors = {
        background = c "base00";
        text = c "base05";
        # Block entities is the slice that matters in thin BT, so it gets the
        # one saturated colour; everything else is deliberately muted so the
        # eye goes straight to it.
        pie1 = c "base0B";
        pie2 = c "base04";
        pie3 = c "base0E";
      };

      border = {
        color = c "base0D";
        width = 3;
        radius = 20;
        padding = 6;
      };

      crosshair = {
        color = c "base08";
        size = 9;
      };

      resolutions = {
        thin = {
          w = 340;
          h = 1080;
        };
        wide = {
          w = 1920;
          h = 300;
        };
        tall = {
          w = 384;
          h = 16384;
        };
      };

      # Measured in-game values; the tall figure is not derivable from the
      # normal one because the vertical FOV changes with the aspect ratio.
      sensitivity = {
        base = 3.7385416219369882;
        tall = 0.25219978149188543;
      };

      repeat_rate = 50;
      repeat_delay = 225;

      layouts = {
        # Search-crafting layout, generated by modules/hardware/mcsr_keyboard.nix.
        mcsr = {
          layout = "mcsr";
          variant = "";
          remaps = {
            "m5" = "f3";
            "capslock" = "0";

            # Ctrl and Shift are swapped so sprint sits under the little
            # finger; D becomes Backspace and Grave/Tab shift along to keep the
            # search-craft keys reachable without moving the left hand.
            "LeftShift" = "LeftCtrl";
            "LeftCtrl" = "LeftShift";
            "D" = "Backspace";
            "Grave" = "Tab";
            "Tab" = "Dot";
          };
        };

        # Fallback for typing in chat or on the wall.
        alt = {
          layout = "us";
          variant = "dvorak";
          remaps = {};
        };
      };

      panel = {
        # Centred in the strip of canvas left of/right of the game column: the
        # thin and tall viewports both sit in the middle, so this cluster owns
        # the right third.
        ecount = {
          x = 1390;
          y = 240;
          scale = 5.0;
        };
        pie = {
          x = 1380;
          y = 380;
          scale = 0.75;
        };
        percent = {
          x = 1455;
          y = 730;
          scale = 5.0;
        };
      };

      measure = {
        # 736x414 is 16:9, matching the canvas, because the pixel ruler PNG is
        # authored on a full 1920x1080 canvas and is drawn into this rectangle.
        x = 16;
        y = 333;
        width = 736;
        height = 414;
        # resources/overlay.png marks 18 cells (9 each side of centre) spanning
        # 1152 of its 1920 px, i.e. 64 canvas px per cell. One cell has to be
        # one render pixel for the ruler to mean anything, so the slice is
        # 1920 / 64 = 30 render pixels wide.
        srcWidth = 30;
        srcHeight = 580;
        overlay = "${inputs.waywall}/resources/overlay.png";
      };

      ninb = {
        anchor = "topright";
        command = "ninjabrain-bot";
        process = "ninjabrain-bot";
      };

      cps = {
        command = "${waywallPkgs.cps-wl}/bin/cps-overlay";
        process = "cps-overlay";
      };

      resizeAnimation = {
        # Feeds ~/.waywall_state, which resize_animation_waywall.py reads inside
        # OBS to tween the capture transform on every resolution change.
        enable = true;
      };

      keys = {
        thin = "*-m4";
        wide = "*-shift-m4";
        tall = "*-f1";
        lowest = "*-ctrl-4";
        switch_layout = "*-ctrl-6";
        ninbot = "*-ctrl-k";
        cps = "*-ctrl-7";
        crosshair = "*-ctrl-8";
      };
    };

    # Transcribed from the prefs.xml this replaces, so the calculator behaves
    # exactly as it did before it became declarative. The hotkey `key` values
    # are raw jnativehook codes: 0xE00 | scancode, i.e. the numpad block with
    # NumLock off, hence the un-round numbers.
    programs.ninjabrain-bot = {
      enable = true;
      stylix = true;
      inherit base16Scheme;

      settings = {
        # Must match Minecraft's sensitivity slider exactly, or every eye throw
        # comes out skewed.
        sensitivity = 0.02291165;
        sensitivity_manual = 0.02291165;
        # Assumed aim error for boat measurements, in degrees.
        sigma_boat = 7.0e-4;

        view = "basic";
        angle_adjustment_type = "tall";
        angle_adjustment_display_type = "increments";
        default_boat_type = "green";

        auto_reset = true;
        color_negative_coords = true;
        direction_help_enabled = true;
        mismeasure_warning_enabled = true;
        show_angle_errors = true;
        show_angle_updates = true;
        use_precise_angle = true;

        language_v2 = "en-US";
        window_x = 961;
        window_y = 36;

        hotkey_redo = stdKey 3655; # numpad 7
        hotkey_lock = stdKey 3657; # numpad 9
        hotkey_decrement = stdKey 3663; # numpad 1
        hotkey_increment = stdKey 3665; # numpad 3
        hotkey_undo = stdKey 3666; # numpad 0
        hotkey_reset = stdKey 3667; # numpad .
        hotkey_boat = stdKey 43; # backslash
      };
    };
  };
}
