spotify_client_id: ENC[AES256_GCM,data:EYTSciYMWp7cbQdxDfqc2OlTF9iqxbeFAGSdAyeBt5A=,iv:gSlVOX2b1XNVZKn7iEl4kFgKVOpLZuXkdMNMOIWs2hU=,tag:X8f901rrWc0V8ao6ZVLneA==,type:str]
github_token: ENC[AES256_GCM,data:ZtrNsPSQBtJCQuvPct7/PqNc5jvBgz4Us3kAj297R1LV481MV5iYfg==,iv:LpGfhHsclLeAmhgroZJKPdhE4jTDnEDqtxHIGaZHEPM=,tag:5VAq4L5WLzSlgqqkig+WUg==,type:str]
sops:
    age:
        - recipient: age1tgengcm9ph3zc96f5gpkkad6at6zru5tkclh3dy953yw0fdl950smww7ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UlRlZ1l2cDZnY1VmcUZN
            SlNiUFFjc215cG0zaGszcEo2K2lzVzdnNEhRCmZRNTc5eHlkR2xHdGUxdVYxTlVH
            NFBobUtIbHlZeDB4VnZnRzRrdFhHK1kKLS0tIFhadFBSUkx3SENyMHNUT21kWHpT
            VUVyVGwydmdYYUd0SW1URlFBNDBjbUEKeroMUBbas+IBI9VREdApErJgiaHobvEA
            U8OAhbULawq6N2T4i44LzWvOm1GUMjnXftGO/9TCWC50qJXC7eyG8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T20:58:13Z"
    mac: ENC[AES256_GCM,data:kTTLWk3FDyJ0rTRBHqmeLO3obBpY/M/xcypvE+IYF/2QIoMTU+j/l076zBRo0xe35gBfuSDxrdW8q9a+ygrf3nyxsQjK36PbOca4eUe1BM5j+0NtNIz8gQvgfQHOlc15x2kRGCPZgp8zFMGCng+LOO84h0UOwVI5kwaXKQ3sLK0=,iv:ct3UUVW/BuMLuasMQ9szvqsoQFCruwxSRVHJQWHqIpM=,tag:KBGffDJr5QVVfFuLqNiw4g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
