spotify_client_id: ENC[AES256_GCM,data:EYTSciYMWp7cbQdxDfqc2OlTF9iqxbeFAGSdAyeBt5A=,iv:gSlVOX2b1XNVZKn7iEl4kFgKVOpLZuXkdMNMOIWs2hU=,tag:X8f901rrWc0V8ao6ZVLneA==,type:str]
github_token: ENC[AES256_GCM,data:ZtrNsPSQBtJCQuvPct7/PqNc5jvBgz4Us3kAj297R1LV481MV5iYfg==,iv:LpGfhHsclLeAmhgroZJKPdhE4jTDnEDqtxHIGaZHEPM=,tag:5VAq4L5WLzSlgqqkig+WUg==,type:str]
matrix_recovery: ENC[AES256_GCM,data:Jlqt7y5MQoVR+UC5Y2nkTJH5xjst1josv/kQE9YFUvJdIHArMY8LLpJW0luGf9zptmfjCCDSnDTtPbw=,iv:HthpXonFej/sNms1HmZ+BdWsLDbU/w7HDsPA1afZD/w=,tag:cbHUo98gTxX2yEILFefMrw==,type:str]
master: ENC[AES256_GCM,data:2Wk+DrX7gno/5Jd5wksoJXOJ4TCdc4ky2HDUsEW0UOevMFciMsk8h35AbGFP8hLBSQ4TKUIh7+GGIDaPtap+UPhaZjdsDDgj7Zo=,iv:gUovlHzdKe80G+94GNQ4fE2nmMYgzTWQIk5a6lt/4ZA=,tag:pDIkjQrH2BFwUJL9gbonHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UlRlZ1l2cDZnY1VmcUZN
            SlNiUFFjc215cG0zaGszcEo2K2lzVzdnNEhRCmZRNTc5eHlkR2xHdGUxdVYxTlVH
            NFBobUtIbHlZeDB4VnZnRzRrdFhHK1kKLS0tIFhadFBSUkx3SENyMHNUT21kWHpT
            VUVyVGwydmdYYUd0SW1URlFBNDBjbUEKeroMUBbas+IBI9VREdApErJgiaHobvEA
            U8OAhbULawq6N2T4i44LzWvOm1GUMjnXftGO/9TCWC50qJXC7eyG8Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tgengcm9ph3zc96f5gpkkad6at6zru5tkclh3dy953yw0fdl950smww7ha
    lastmodified: "2026-07-29T19:27:02Z"
    mac: ENC[AES256_GCM,data:nsVVn25GSjBI1otJ2hFlaD/seZB66mIcF1gR1mHeLHbfW1iMAeaXzTJqeI0dcHBIKzpslmuL6jm2csdsk5QMC68bVrXCCoN2zt+jXg7hCKAd8XpZhfWq3AiABlMEy0b/3wfyaFr4NSRkTCOKy5JJAKYwiAo/cNT6YxdwAmyUo9s=,iv:jUlWVzQKF98iANlEgMffUZgYIwtK2bLd48HkMu7Lctc=,tag:uQCcaN+t3bmTwP/64cGDBA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
