spotify_client_id: ENC[AES256_GCM,data:EYTSciYMWp7cbQdxDfqc2OlTF9iqxbeFAGSdAyeBt5A=,iv:gSlVOX2b1XNVZKn7iEl4kFgKVOpLZuXkdMNMOIWs2hU=,tag:X8f901rrWc0V8ao6ZVLneA==,type:str]
github_token: ENC[AES256_GCM,data:ZtrNsPSQBtJCQuvPct7/PqNc5jvBgz4Us3kAj297R1LV481MV5iYfg==,iv:LpGfhHsclLeAmhgroZJKPdhE4jTDnEDqtxHIGaZHEPM=,tag:5VAq4L5WLzSlgqqkig+WUg==,type:str]
matrix_recovery: ENC[AES256_GCM,data:Jlqt7y5MQoVR+UC5Y2nkTJH5xjst1josv/kQE9YFUvJdIHArMY8LLpJW0luGf9zptmfjCCDSnDTtPbw=,iv:HthpXonFej/sNms1HmZ+BdWsLDbU/w7HDsPA1afZD/w=,tag:cbHUo98gTxX2yEILFefMrw==,type:str]
matrix_bot_recovery: ENC[AES256_GCM,data:6E5uiPiOeZqy2s9WZp+ETN1WVg+mvRpheE+qdRr3EZsrGzyU9ZX5/gIHjy3VMVw/BjZKQiZCbb5Vpqo=,iv:gqfZpvMJQJHziTflVPQ7b8xgVpywcVPExU3coebuJq4=,tag:BWOx16vSOg8qvc+rIsmEKw==,type:str]
master: ENC[AES256_GCM,data:2Wk+DrX7gno/5Jd5wksoJXOJ4TCdc4ky2HDUsEW0UOevMFciMsk8h35AbGFP8hLBSQ4TKUIh7+GGIDaPtap+UPhaZjdsDDgj7Zo=,iv:gUovlHzdKe80G+94GNQ4fE2nmMYgzTWQIk5a6lt/4ZA=,tag:pDIkjQrH2BFwUJL9gbonHQ==,type:str]
sops:
    age:
        - recipient: age1tgengcm9ph3zc96f5gpkkad6at6zru5tkclh3dy953yw0fdl950smww7ha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UlRlZ1l2cDZnY1VmcUZN
            SlNiUFFjc215cG0zaGszcEo2K2lzVzdnNEhRCmZRNTc5eHlkR2xHdGUxdVYxTlVH
            NFBobUtIbHlZeDB4VnZnRzRrdFhHK1kKLS0tIFhadFBSUkx3SENyMHNUT21kWHpT
            VUVyVGwydmdYYUd0SW1URlFBNDBjbUEKeroMUBbas+IBI9VREdApErJgiaHobvEA
            U8OAhbULawq6N2T4i44LzWvOm1GUMjnXftGO/9TCWC50qJXC7eyG8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T14:58:04Z"
    mac: ENC[AES256_GCM,data:EWlyUdgzky8KA4PtqYle/1GIu8tOd9g1OCOhwq+qxrmpVNk8zxzv+b/2MtFXaG1aKepY3/ohxO44LJ2gvRlgZDaBFRYb4M3/FiaKJF/tzdAJtw6gMcxzSFYk8NEvRfHagEiUhFKW0mxqusNZ0YbT9sI06VJaEN1fYXmDJyHna90=,iv:8Riqd8BINcr4RyWCORhqirYhpdMLp+L7QEKbB4jos5Y=,tag:lnSPl5k69YjzUW29Gg1njA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
